//Очистка экрана (перед сменой символа,вспомогательная функция)
function clearScreen(nameVarTD){
	for (var i = 0; i < nameVarTD.length; i++) {
		nameVarTD[i].className = "";
	};
};
//Отображения цифр
function numberZero(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[21].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[28].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[35].className = colorStyle;
	screenLEDTD[40].className = colorStyle;
	screenLEDTD[42].className = colorStyle;
	screenLEDTD[47].className = colorStyle;
	screenLEDTD[49].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[56].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[63].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[70].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
};
function numberOne(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[9].className = colorStyle;
	screenLEDTD[10].className = colorStyle;
	screenLEDTD[15].className = colorStyle;
	screenLEDTD[17].className = colorStyle;
	screenLEDTD[24].className = colorStyle;
	screenLEDTD[31].className = colorStyle;
	screenLEDTD[38].className = colorStyle;
	screenLEDTD[45].className = colorStyle;
	screenLEDTD[52].className = colorStyle;
	screenLEDTD[59].className = colorStyle;
	screenLEDTD[66].className = colorStyle;
	screenLEDTD[73].className = colorStyle;
	screenLEDTD[80].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
	screenLEDTD[89].className = colorStyle;
};
function numberTwo(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[40].className = colorStyle;
	screenLEDTD[46].className = colorStyle;
	screenLEDTD[52].className = colorStyle;
	screenLEDTD[58].className = colorStyle;
	screenLEDTD[64].className = colorStyle;
	screenLEDTD[70].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[84].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
	screenLEDTD[89].className = colorStyle;
};
function numberThree(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[40].className = colorStyle;
	screenLEDTD[44].className = colorStyle;
	screenLEDTD[45].className = colorStyle;
	screenLEDTD[46].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
};
function numberFour(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[0].className = colorStyle;
	screenLEDTD[5].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[21].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[28].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[35].className = colorStyle;
	screenLEDTD[40].className = colorStyle;
	screenLEDTD[43].className = colorStyle;
	screenLEDTD[44].className = colorStyle;
	screenLEDTD[45].className = colorStyle;
	screenLEDTD[46].className = colorStyle;
	screenLEDTD[47].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[89].className = colorStyle;
};
function numberFive(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[0].className = colorStyle;
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[5].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[21].className = colorStyle;
	screenLEDTD[28].className = colorStyle;
	screenLEDTD[36].className = colorStyle;
	screenLEDTD[37].className = colorStyle;
	screenLEDTD[38].className = colorStyle;
	screenLEDTD[39].className = colorStyle;
	screenLEDTD[47].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
};
function numberSix(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[21].className = colorStyle;
	screenLEDTD[28].className = colorStyle;
	screenLEDTD[35].className = colorStyle;
	screenLEDTD[36].className = colorStyle;
	screenLEDTD[37].className = colorStyle;
	screenLEDTD[38].className = colorStyle;
	screenLEDTD[39].className = colorStyle;
	screenLEDTD[42].className = colorStyle;
	screenLEDTD[47].className = colorStyle;
	screenLEDTD[49].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[56].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[63].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[70].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
};
function numberSeven(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[0].className = colorStyle;
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[5].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[39].className = colorStyle;
	screenLEDTD[46].className = colorStyle;
	screenLEDTD[52].className = colorStyle;
	screenLEDTD[59].className = colorStyle;
	screenLEDTD[65].className = colorStyle;
	screenLEDTD[72].className = colorStyle;
	screenLEDTD[79].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
};
function numberEight(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[21].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[28].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[35].className = colorStyle;
	screenLEDTD[40].className = colorStyle;
	screenLEDTD[43].className = colorStyle;
	screenLEDTD[44].className = colorStyle;
	screenLEDTD[45].className = colorStyle;
	screenLEDTD[46].className = colorStyle;
	screenLEDTD[49].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[56].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[63].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[70].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
};
function numberNine(colorStyle,idLED) {
	var screenLED = document.getElementById (idLED);
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[1].className = colorStyle;
	screenLEDTD[2].className = colorStyle;
	screenLEDTD[3].className = colorStyle;
	screenLEDTD[4].className = colorStyle;
	screenLEDTD[7].className = colorStyle;
	screenLEDTD[12].className = colorStyle;
	screenLEDTD[14].className = colorStyle;
	screenLEDTD[19].className = colorStyle;
	screenLEDTD[21].className = colorStyle;
	screenLEDTD[26].className = colorStyle;
	screenLEDTD[28].className = colorStyle;
	screenLEDTD[33].className = colorStyle;
	screenLEDTD[35].className = colorStyle;
	screenLEDTD[40].className = colorStyle;
	screenLEDTD[42].className = colorStyle;
	screenLEDTD[47].className = colorStyle;
	screenLEDTD[50].className = colorStyle;
	screenLEDTD[51].className = colorStyle;
	screenLEDTD[52].className = colorStyle;
	screenLEDTD[53].className = colorStyle;
	screenLEDTD[54].className = colorStyle;
	screenLEDTD[61].className = colorStyle;
	screenLEDTD[68].className = colorStyle;
	screenLEDTD[75].className = colorStyle;
	screenLEDTD[77].className = colorStyle;
	screenLEDTD[82].className = colorStyle;
	screenLEDTD[85].className = colorStyle;
	screenLEDTD[86].className = colorStyle;
	screenLEDTD[87].className = colorStyle;
	screenLEDTD[88].className = colorStyle;
};
//Отображения пиктограмм
function stand() {
	var screenLED = document.getElementById ("topLED");
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[6].className = "redLight";
	screenLEDTD[13].className = "redLight";
	screenLEDTD[26].className = "redLight";
	screenLEDTD[27].className = "redLight";
	screenLEDTD[32].className = "redLight";
	screenLEDTD[34].className = "redLight";
	screenLEDTD[39].className = "redLight";
	screenLEDTD[41].className = "redLight";
	screenLEDTD[46].className = "redLight";
	screenLEDTD[48].className = "redLight";
	screenLEDTD[53].className = "redLight";
	screenLEDTD[55].className = "redLight";
	screenLEDTD[62].className = "redLight";
	screenLEDTD[69].className = "redLight";
	screenLEDTD[76].className = "redLight";
	screenLEDTD[83].className = "redLight";
	screenLEDTD[89].className = "redLight";
	screenLEDTD[90].className = "redLight";
	screenLEDTD[91].className = "redLight";
	screenLEDTD[98].className = "redLight";
	screenLEDTD[112].className = "redLight";
	screenLEDTD[113].className = "redLight";
	screenLEDTD[119].className = "redLight";
	screenLEDTD[121].className = "redLight";
	screenLEDTD[126].className = "redLight";
	screenLEDTD[128].className = "redLight";
	screenLEDTD[133].className = "redLight";
	screenLEDTD[135].className = "redLight";
	screenLEDTD[140].className = "redLight";
	screenLEDTD[142].className = "redLight";
	screenLEDTD[147].className = "redLight";
	screenLEDTD[154].className = "redLight";
	screenLEDTD[161].className = "redLight";
	screenLEDTD[168].className = "redLight";
	screenLEDTD[175].className = "redLight";
	screenLEDTD[176].className = "redLight"; 
};//Пиктограмма "стой"
function move(){
	var screenLED = document.getElementById ("bottomLED");
	var screenLEDTD = screenLED.getElementsByTagName('td');
	clearScreen(screenLEDTD);
	screenLEDTD[6].className = "greenLight";
	screenLEDTD[13].className = "greenLight";
	screenLEDTD[26].className = "greenLight";
	screenLEDTD[27].className = "greenLight";
	screenLEDTD[30].className = "greenLight";
	screenLEDTD[32].className = "greenLight";
	screenLEDTD[34].className = "greenLight";
	screenLEDTD[38].className = "greenLight";
	screenLEDTD[41].className = "greenLight";
	screenLEDTD[48].className = "greenLight";
	screenLEDTD[55].className = "greenLight";
	screenLEDTD[61].className = "greenLight";
	screenLEDTD[68].className = "greenLight";
	screenLEDTD[74].className = "greenLight";
	screenLEDTD[81].className = "greenLight";
	screenLEDTD[87].className = "greenLight";
	screenLEDTD[88].className = "greenLight";
	screenLEDTD[91].className = "greenLight";
	screenLEDTD[98].className = "greenLight";
	screenLEDTD[112].className = "greenLight";
	screenLEDTD[113].className = "greenLight";
	screenLEDTD[119].className = "greenLight";
	screenLEDTD[121].className = "greenLight";
	screenLEDTD[126].className = "greenLight";
	screenLEDTD[129].className = "greenLight";
	screenLEDTD[133].className = "greenLight";
	screenLEDTD[136].className = "greenLight";
	screenLEDTD[140].className = "greenLight";
	screenLEDTD[148].className = "greenLight";
	screenLEDTD[155].className = "greenLight";
	screenLEDTD[163].className = "greenLight";
	screenLEDTD[170].className = "greenLight";
	screenLEDTD[176].className = "greenLight";
	screenLEDTD[177].className = "greenLight";
};//Пиктограмма "иди"
//Режим "Выключено"(на случай добавления новых возможностей)
function modeOff() {
	var screenLEDTD = document.getElementsByTagName('td');
	clearScreen(screenLEDTD);
};
//Переключение цифр с интервалом 1 сек
function switchNumOneSecInt(colorStyle,idLED){
	function cycle(){
		setTimeout(numberZero, 1000, colorStyle,idLED);
		setTimeout(numberNine, 2000, colorStyle,idLED);
		setTimeout(numberEight, 3000, colorStyle,idLED);
		setTimeout(numberSeven, 4000, colorStyle,idLED);
		setTimeout(numberSix, 5000, colorStyle,idLED);
		setTimeout(numberFive, 6000, colorStyle,idLED);
		setTimeout(numberFour, 7000, colorStyle,idLED);
		setTimeout(numberThree, 8000, colorStyle,idLED);
		setTimeout(numberTwo, 9000, colorStyle,idLED);
		setTimeout(numberOne, 10000, colorStyle,idLED);
	};
	cycle();
	var IntID = setInterval(cycle, 10000);
	setTimeout(function(){
		clearInterval(IntID);
	}, 10000);
};
//Переключение цифр с интервалом 10 сек
function switchNumTenSecInt(colorStyle,idLED){
	setTimeout(numberTwo, 1000, colorStyle,idLED);
	setTimeout(numberOne, 2000, colorStyle,idLED);
	setTimeout(numberZero, 12000, colorStyle,idLED);
};
//Весь зеленый свет
function greenLight(){
	switchNumOneSecInt("greenLight","topRightLED");
	switchNumTenSecInt("greenLight","topLeftLED");
	setTimeout(move, 1000);
};
//Весь красный свет
function redLight(){
	switchNumOneSecInt("redLight","bottomRightLED");
	switchNumTenSecInt("redLight","bottomLeftLED");
	setTimeout(stand, 1000);
};
/*--------------------------РАБОТА СВЕТОФОРА*--------------------------*/
greenLight();
setTimeout(redLight, 20000);
setInterval(function(){
	greenLight();
	setTimeout(redLight, 20000);
}, 40000);


